### ISSUE TITLE
Part 2: Transitioning AIP RFCs to the accepted status

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#647]
From Part 1 #632 , work to do and RFCs left to process:

- [x] Merge? 0434 -- @b1conrad will add a PR to change the language around URL Shortening - PR #639 
- [x] Merged: 0183 -- @smithbk to add a PR to reference V2 Issue/Present (RFC 0453/0454); change "credential_id" to "thread_id" to indicate that the related credential, reference that if multiples of credential are issued they are the same data/different format; add note that this is not a security issue if done/not done; add please-ack. #636 MERGED
- [x] Merge? 0317 -- @TimoGlastra -- to take a pass at cleaning up this RFC and we'd like to include it in AIP 2.0 PR #644 
- [ ] 0627 -- @swcurran -- Need a community update transition --- issue and then RFC - NOT DONE
- [ ] 0510 -- @TimoGlastra @llorllale -- to use Issue #598 to do a PR to RFC 0510
- [x] Discuss: 0646 -- @TimoGlastra to write that one - #646 
- [x] 0627 - Resolved to be move to Accepted at the last meeting

Remaining RFCs to be "accepted":

#### AIP 2.0 Base

- [ ] Feature | [0434-outofband](https://github.com/hyperledger/aries-rfcs/tree/b982c24b9083dd5dddff6343dbf534cd1cfe36a6/features/0434-outofband) | :new:
- [ ] Feature | [0183-revocation-notification](https://github.com/hyperledger/aries-rfcs/tree/b982c24b9083dd5dddff6343dbf534cd1cfe36a6/features/0183-revocation-notification) | :new:
- [x] Feature | [0627-static-peer-dids](https://github.com/hyperledger/aries-rfcs/tree/b982c24b9083dd5dddff6343dbf534cd1cfe36a6/features/0627-static-peer-dids)  | :new:

#### LDCRED: JSON-LD Based Credentials

- [ ] Feature | [0510-dif-pres-exch-attach](https://github.com/hyperledger/aries-rfcs/tree/b982c24b9083dd5dddff6343dbf534cd1cfe36a6/features/0510-dif-pres-exch-attach) | :new:

#### BBSCRED: BBS+ Based Credentials
- [ ] Feature | [PR 0646-bbs-credentials] #646 | :new:

#### DIFPX: DIF Presentation Exchange Support

- [ ] Feature | [0510-dif-pres-exch-attach](https://github.com/hyperledger/aries-rfcs/tree/b982c24b9083dd5dddff6343dbf534cd1cfe36a6/features/0510-dif-pres-exch-attach) | :new:

**Comment by swcurran** [comment]
Updates:

- @TimoGlastra to update the `~please_ack` decorator PR #644 to allow both RECEIPT and OUTCOME on message - e.g. an array.
- @smithbk to update revocation PR #636 to adjust the use of `~please_ack`
- @b1conrad to update the PR from base so we can merge #639 @TelegramSam to add note for @dhh1128 
- @TimoGlastra to do a new PR with some small cleanup to #646

**Comment by swcurran** [comment]
@TelegramSam ^^ in case you were notified because you were added via an edit.  Enjoy!

**Comment by swcurran** [comment]
All of these tasks have been completed.  @TelegramSam --- this can be closed before or at the 2021.05.26 Aries WG Meeting.

**Comment by TimoGlastra** [comment]
Closing this issue as AIP 2.0 has been released for a while
